// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
/// EUDAMED is the IT system established by Regulation (EU) 2017/745 on medical devices and Regulation (EU) 2017/746 on in vitro diagnosis medical devices. EUDAMED provides a living picture of the lifecycle of medical devices that are made available in the European Union (EU) and aims to enhance overall transparency, including better access to information for public and healthcare professionals, and to enhance coordination between the different Member States in the EU.
///
/// Field-level documentation below draws on general MDR/IVDR and UDI domain knowledge, cross-referenced with the community-maintained, reverse-engineered EUDAMED API reference at https://github.com/openregulatory/eudamed-api (which documents EUDAMED's internal UI API rather than this public Datalake API). Where the exact meaning of a field could not be confirmed, the description is phrased as a best-effort interpretation.
///
///
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// actors
    ///
    /// Search economic operators (manufacturers, authorised representatives, importers, producers, etc.) registered in EUDAMED. Corresponds to the results shown on the EUDAMED "Actors" search page.
    ///
    /// - Remark: HTTP `GET /actors`.
    /// - Remark: Generated from `#/paths//actors/get(getActors)`.
    public func getActors(_ input: Operations.getActors.Input) async throws -> Operations.getActors.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getActors.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/actors",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "ACTOR_ID",
                    value: input.query.ACTOR_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "NAME",
                    value: input.query.NAME
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "ABBREVIATED_NAME",
                    value: input.query.ABBREVIATED_NAME
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "ACTOR_TYPE",
                    value: input.query.ACTOR_TYPE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "CA_NAME",
                    value: input.query.CA_NAME
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "CA_ACTOR_ID",
                    value: input.query.CA_ACTOR_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "ACT_COUNTRY_ISO2_CODE",
                    value: input.query.ACT_COUNTRY_ISO2_CODE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "format",
                    value: input.query.format
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "$after",
                    value: input.query._dollar_after
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "api-version",
                    value: input.query.api_hyphen_version
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.getActors.Output.Ok.Headers = .init(
                        date: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "date",
                            as: Swift.String.self
                        ),
                        content_hyphen_length: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "content-length",
                            as: Swift.Int.self
                        ),
                        connection: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "connection",
                            as: Swift.String.self
                        ),
                        x_hyphen_ms_hyphen_correlation_hyphen_id: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "x-ms-correlation-id",
                            as: Swift.String.self
                        ),
                        request_hyphen_context: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "request-context",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getActors.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ActorResponse.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// reference
    ///
    /// Look up EUDAMED reference/nomenclature data (code lists), such as actor types, risk classes, applicable legislation, and device statuses, which are referenced by ID or code from the other endpoints.
    ///
    /// - Remark: HTTP `GET /reference`.
    /// - Remark: Generated from `#/paths//reference/get(getReference)`.
    public func getReference(_ input: Operations.getReference.Input) async throws -> Operations.getReference.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getReference.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/reference",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "ID",
                    value: input.query.ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "CODE",
                    value: input.query.CODE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "LANGUAGE",
                    value: input.query.LANGUAGE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "format",
                    value: input.query.format
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "$after",
                    value: input.query._dollar_after
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "api-version",
                    value: input.query.api_hyphen_version
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.getReference.Output.Ok.Headers = .init(
                        date: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "date",
                            as: Swift.String.self
                        ),
                        content_hyphen_length: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "content-length",
                            as: Swift.Int.self
                        ),
                        connection: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "connection",
                            as: Swift.String.self
                        ),
                        x_hyphen_ms_hyphen_correlation_hyphen_id: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "x-ms-correlation-id",
                            as: Swift.String.self
                        ),
                        request_hyphen_context: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "request-context",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getReference.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.ReferenceResponse.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// udi
    ///
    /// Search Unique Device Identification (UDI) records, i.e. the devices registered in EUDAMED, identified by their Basic UDI-DI and (primary) UDI-DI. Corresponds to the results shown on the EUDAMED "Devices" search page.
    ///
    /// - Remark: HTTP `GET /udi`.
    /// - Remark: Generated from `#/paths//udi/get(getUdi)`.
    public func getUdi(_ input: Operations.getUdi.Input) async throws -> Operations.getUdi.Output {
        try await client.send(
            input: input,
            forOperation: Operations.getUdi.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/udi",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "PRIMARY_DI",
                    value: input.query.PRIMARY_DI
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "BASIC_UDI",
                    value: input.query.BASIC_UDI
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "TRADE_NAME",
                    value: input.query.TRADE_NAME
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "DEVICE_NAME",
                    value: input.query.DEVICE_NAME
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "DEVICE_MODEL",
                    value: input.query.DEVICE_MODEL
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "REFERENCE",
                    value: input.query.REFERENCE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "NOMENCLATURE_CODE",
                    value: input.query.NOMENCLATURE_CODE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "RISK_CLASS_ID",
                    value: input.query.RISK_CLASS_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "APPLICABLE_LEGISLATION_ID",
                    value: input.query.APPLICABLE_LEGISLATION_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "PLACED_ON_THE_MARKET_ID",
                    value: input.query.PLACED_ON_THE_MARKET_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "MF_SRN",
                    value: input.query.MF_SRN
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "SPECIAL_DEVICE_TYPE_ID",
                    value: input.query.SPECIAL_DEVICE_TYPE_ID
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "MEDICAL_PURPOSE",
                    value: input.query.MEDICAL_PURPOSE
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "format",
                    value: input.query.format
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "$after",
                    value: input.query._dollar_after
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "api-version",
                    value: input.query.api_hyphen_version
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let headers: Operations.getUdi.Output.Ok.Headers = .init(
                        date: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "date",
                            as: Swift.String.self
                        ),
                        content_hyphen_length: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "content-length",
                            as: Swift.Int.self
                        ),
                        connection: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "connection",
                            as: Swift.String.self
                        ),
                        x_hyphen_ms_hyphen_correlation_hyphen_id: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "x-ms-correlation-id",
                            as: Swift.String.self
                        ),
                        request_hyphen_context: try converter.getOptionalHeaderFieldAsURI(
                            in: response.headerFields,
                            name: "request-context",
                            as: Swift.String.self
                        )
                    )
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.getUdi.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UdiDeviceResponse.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(
                        headers: headers,
                        body: body
                    ))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
